### ISSUE TITLE
Getting an error while starting

### ISSUE THREAD

**Issue by Mohsin05** [punkave/apostrophe-localization#11]
Hello, Good day, 
I have successfully installed the project. While following the documentation I have install the apostrophe-localization module. In the app.js I have placed the  
  modules: {
            // Add custom apostrophe-modules and their respective configuration here!
            'apostrophe-localization': {
                defaultLocale: 'en',
                locales: {'en': 'English', 'es': 'Español'}
            }
        }

When I start the project I get this error.

Template render error: (apostrophe-pages:pages/home.html)
  Error: Unable to call `aposLocalePicker`, which is undefined or falsey
------------------------------------------------------------------------------------
More over I have another issue while configuring the project in the repository there is file 

https://github.com/punkave/apostrophe-localization/blob/master/index.js

I can understand that it is detecting the URL and detect the language and setting the local variable but I am not able to understand that how to make use of it. I mean to say where to place the code and how to make that file into work. if I place that file into the root directory it does not work that is for sure because there is on link to that file. 
I am sure I am missing some thing. 
Please help me out. 
Thank you very much.

**Comment by boutell** [comment]
I believe you are attempting to use this module with Apostrophe 2.x. This module is deprecated and only for use with Apostrophe 0.5.x.

I have published an update with a clear deprecation notice. Sorry for the confusion.

In Apostrophe 2.x you can localize sites with the new apostrophe-workflow module, which is greatly superior in all aspects and fully supports localization.
