### ISSUE TITLE
how hide  areas or pages that wasn't translated

### ISSUE THREAD

**Issue by pipinov** [punkave/apostrophe-localization#4]
Hi!
Is there a way to hide areas or pages that not translated?

Thanks!

**Comment by boutell** [comment]
This would be difficult to write a good query for. I would suggest using a
tag to track whether pages are good enough for each language yet and then
looking for that flag.

On Sat, Dec 5, 2015 at 10:25 AM, Alexandr Pipinov notifications@github.com
wrote:

> Hi!
> Is there a way to hide areas or pages that not translated?
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/punkave/apostrophe-localization/issues/4.

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
You could write a page loader function with logic similar to that in the
"/report" route in the localization module.

On Mon, Dec 7, 2015 at 10:39 AM, Tom Boutell tom@punkave.com wrote:

> This would be difficult to write a good query for. I would suggest using a
> tag to track whether pages are good enough for each language yet and then
> looking for that flag.
> 
> On Sat, Dec 5, 2015 at 10:25 AM, Alexandr Pipinov <
> notifications@github.com> wrote:
> 
> > Hi!
> > Is there a way to hide areas or pages that not translated?
> > 
> > Thanks!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/punkave/apostrophe-localization/issues/4.
> 
> ## 
> 
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by petershaw** [comment]
The localeObject should return an flag if the page is translated or not. 

```
      var localeObject = {
        key: locale,
        label: label,
        url: newUrl,
        translated: true
        active: (currentLocale === locale)
      };
```

but i can not figure out, how to get the current page at this function. Therefor i could not query the database to look for the key that local provide.

**Comment by petershaw** [comment]
What we can do is to call the picker with the page as an attribute: 

```
{{ aposLocalePicker(page) }}
```

and than look for the localized attribute in the `self._apos.addLocal('aposLocalePicker', function(args) {` function.

```
console.log(
      "##"
    , _.keys(args.localized)
)
```

If the key is not present, than the new translated flag is set to false. 

Hm, maybe there is an better solution?

**Comment by petershaw** [comment]
I left a pull request. Hope you like it.
