### ISSUE TITLE
Unable to call `aposLocalePicker`

### ISSUE THREAD

**Issue by AttilaSATAN** [punkave/apostrophe-localization#8]
When I add `{{ aposLocalePicker() }}` to the outerLayout.html as mentioned in the docs. I got this error

```
:: 2016-05-06T22:02:43+0300: outer layout error at /
Current user: admin
{ [Template render error: (D:\Dev\Playground\apostrophe\apostrophe-sandbox-2\apostrophe-sandbox\views\global\outerLayout.html) [Line 53, Column 20]
Error: Unable to call `aposLocalePicker`, which is undefined or falsey] name: 'Template render error' }
```

I'm using windows 10 with `node -v` `v5.9.0`

I tried some debuging and realized that apostrophe-localization module does not initiates at all.

**Comment by boutell** [comment]
Did you add it to your modules: { ... } block in app.js?

On Fri, May 6, 2016 at 3:08 PM, Attila SATAN notifications@github.com
wrote:

> When I add {{ aposLocalePicker() }} to the outerLayout.html as mentioned
> in the docs. I got this error
> 
> :: 2016-05-06T22:02:43+0300: outer layout error at /
> Current user: admin
> { [Template render error: (D:\Dev\Playground\apostrophe\apostrophe-sandbox-2\apostrophe-sandbox\views\global\outerLayout.html) [Line 53, Column 20]
> Error: Unable to call `aposLocalePicker`, which is undefined or falsey] name: 'Template render error' }
> 
> I'm using windows 10 with node -v v5.9.0
> 
> I tried some debuging and realized that apostrophe-localization module
> does not initiates at all.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/punkave/apostrophe-localization/issues/8

## 

*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by AttilaSATAN** [comment]
Ups! :) I've toughed that all of the init options object was actually modules.
